default_timeout_in_minutes: 90
icon_image: alarm_icon.png
max_timeout_in_minutes: 120
min_timeout_in_minutes: 20
pre_title: Time to
startup_timeout_in_minutes: 90
title: Exercise
title_color: '#FFFFFF'
window_background_color: '#004080'
window_title: Exercise reminder
